apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: leonomano-do-k8s-cluster-minikube-argowf-keys
  namespace: argo
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-dev-parameter-store
  target:
    name: leonomano-do-k8s-cluster-minikube-argowf-keys
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: /account-configuration/dev/minikube_argo_provisioner_access_keys
